apiVersion: v1
kind: Service
metadata:
  name: waitroom-service
spec:
  selector:
    app: waitroom
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: localhost
